## Employee Data Cleaning & Transformation ETL Pipeline using python

### Overview

This project demonstrates an ETL (Extract, Transform, Load) pipeline implemented in Python for cleaning, standardizing, and enriching employee data from the csv source.

##### Importing the main package for data transformation
- Panda
- Numpy

In [23]:
import pandas as pd
import numpy as np
import datetime as dt

 Extracting data from csv source, full load method

In [24]:
data_url=r'.\Dataset\Messy_Employee_dataset.csv'
employees_df = pd.read_csv(data_url)

Display all the main information about the data for starting data cleaning

In [25]:
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        1020 non-null   str
 1   first_name         1020 non-null   str
 2   last_name          1020 non-null   str
 3   age                809 non-null    float64
 4   department_region  1020 non-null   str
 5   status             1020 non-null   str
 6   join_date          1020 non-null   str
 7   salary             996 non-null    float64
 8   email              1020 non-null   str
 9   phone              1020 non-null   int64
 10  performance_score  1020 non-null   str
 11  remote_work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), str(8)
memory usage: 88.8 KB

Check the data frame columns and clean it (Strip the spaces and change them to lower cases)

In [26]:
cols = employees_df.columns.str.strip().str.lower()

employees_df.columns=cols
employees_df.head(2)

,employee_id,first_name,last_name,age,department_region,status,join_date,salary,email,phone,performance_score,remote_work
0,emp1000,bob,davis,25.0,devops-california,active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,average,True
1,emp1001,bob,brown,NaN,finance-texas,active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,excellent,True

Check the uniquness of the employee_id column and make it upper

In [27]:
employees_df.employee_id.is_unique
employees_df.employee_id = employees_df['employee_id'].str.upper()
employees_df.head(2)

,employee_id,first_name,last_name,age,department_region,status,join_date,salary,email,phone,performance_score,remote_work
0,EMP1000,bob,davis,25.0,devops-california,active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,average,True
1,EMP1001,bob,brown,NaN,finance-texas,active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,excellent,True

Remove leading/trailing spaces from names and capitalizing them

In [28]:
name=['first_name','last_name']
for col in name:
    employees_df[col] = employees_df[col].str.strip().str.capitalize()

employees_df.head(3)

,employee_id,first_name,last_name,age,department_region,status,join_date,salary,email,phone,performance_score,remote_work
0,EMP1000,Bob,Davis,25.0,devops-california,active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,average,True
1,EMP1001,Bob,Brown,NaN,finance-texas,active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,excellent,True
2,EMP1002,Alice,Jones,NaN,admin-nevada,pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,good,True

Split Department_Region into:
                - Department
                - Region

            Example:
                IT-NorthAmerica
                -> IT
                -> NorthAmerica

In [29]:
employees_df['department']=(employees_df['department_region'].astype(str).str.split('-').str[0]
            .str.capitalize())
employees_df['region']=(employees_df['department_region'].astype(str).str.split('-').str[1]
            .str.capitalize())

employees_df.sample(5)

,employee_id,first_name,last_name,age,department_region,status,join_date,salary,email,phone,performance_score,remote_work,department,region
918,EMP1918,Charlie,Brown,NaN,hr-new york,active,9/14/2024,99567.78,charlie.brown@example.com,-5057303626,good,True,Hr,New york
58,EMP1058,David,Williams,35.0,finance-texas,pending,11/7/2021,93620.88,david.williams@example.com,-54522800,good,False,Finance,Texas
506,EMP1506,Frank,Garcia,NaN,hr-new york,pending,11/30/2024,89077.36,frank.garcia@example.com,-2727423182,average,False,Hr,New york
102,EMP1102,Alice,Johnson,35.0,finance-texas,active,3/31/2022,84422.26,alice.johnson@example.com,-9141612845,average,False,Finance,Texas
106,EMP1106,Bob,Miller,30.0,devops-new york,inactive,9/14/2023,55683.12,bob.miller@example.com,-8071569561,poor,True,Devops,New york

Convert employment status into binary flag

            1 = Active
            0 = Inactive / Pending

In [30]:
try:
    employees_df['status'] = employees_df['status'].apply(lambda x: 1 if str.lower(x) in ['active','pending'] else 0)
except Exception as e:
    print(e)

Check Join_date column is as date or not, if not we will change it type to date

In [31]:
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   employee_id        1020 non-null   str
 1   first_name         1020 non-null   str
 2   last_name          1020 non-null   str
 3   age                809 non-null    float64
 4   department_region  1020 non-null   str
 5   status             1020 non-null   int64
 6   join_date          1020 non-null   str
 7   salary             996 non-null    float64
 8   email              1020 non-null   str
 9   phone              1020 non-null   int64
 10  performance_score  1020 non-null   str
 11  remote_work        1020 non-null   bool
 12  department         1020 non-null   object
 13  region             1020 non-null   object
dtypes: bool(1), float64(2), int64(2), object(2), str(7)
memory usage: 104.7+ KB

In [32]:
employees_df['join_date'].isna().sum()

np.int64(0)

In [33]:
employees_df['join_date'] = pd.to_datetime(employees_df['join_date'])
employees_df.sample(5)

,employee_id,first_name,last_name,age,department_region,status,join_date,salary,email,phone,performance_score,remote_work,department,region
237,EMP1237,Alice,Miller,30.0,finance-illinois,0,2023-02-24,58243.27,alice.miller@example.com,-2184011844,average,False,Finance,Illinois
633,EMP1633,Charlie,Smith,40.0,finance-texas,1,2024-10-07,95981.90,charlie.smith@example.com,-9749096172,average,True,Finance,Texas
378,EMP1378,Heidi,Johnson,40.0,devops-florida,0,2023-12-25,108792.43,heidi.johnson@example.com,-3307704610,poor,True,Devops,Florida
573,EMP1573,David,Johnson,NaN,sales-florida,1,2024-08-13,102649.36,david.johnson@example.com,-2324412335,poor,False,Sales,Florida
801,EMP1801,Bob,Miller,30.0,sales-california,1,2021-10-14,68973.65,bob.miller@example.com,-6248433796,average,True,Sales,California

Checking emails uniqueness and at the same time has the same domain

In [34]:
employees_df['email'] = employees_df['email'].str.strip()
employees_df[employees_df['email'].duplicated()==True]['email'].count()
# the test data quality shows that there are 956 emial is duplicate
# as action we will flag the as a true or false in new column for check it with the stakeholder

np.int64(956)

In [35]:
employees_df['email'].apply(lambda x : True if '@example.com' in x else False).sum()
# all the email has the same domain

np.int64(1020)

In [36]:
employees_df['duplicate_email_flag'] = employees_df['email'].duplicated()
employees_df.sample(5)

,employee_id,first_name,last_name,age,department_region,status,join_date,salary,email,phone,performance_score,remote_work,department,region,duplicate_email_flag
128,EMP1128,David,Brown,NaN,finance-new york,0,2020-03-30,72272.34,david.brown@example.com,-3315377958,average,False,Finance,New york,True
65,EMP1065,Bob,Johnson,40.0,finance-nevada,1,2021-02-02,100284.21,bob.johnson@example.com,-5328632665,excellent,False,Finance,Nevada,False
240,EMP1240,Frank,Johnson,35.0,devops-texas,1,2023-01-15,70325.36,frank.johnson@example.com,-3103032431,average,False,Devops,Texas,True
996,EMP1996,David,Smith,40.0,admin-texas,1,2021-01-28,51939.29,david.smith@example.com,-2442607818,excellent,True,Admin,Texas,True
299,EMP1299,Alice,Garcia,NaN,finance-nevada,0,2024-01-21,51523.93,alice.garcia@example.com,-18418619,average,True,Finance,Nevada,True

In [37]:
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           1020 non-null   str
 1   first_name            1020 non-null   str
 2   last_name             1020 non-null   str
 3   age                   809 non-null    float64
 4   department_region     1020 non-null   str
 5   status                1020 non-null   int64
 6   join_date             1020 non-null   datetime64[us]
 7   salary                996 non-null    float64
 8   email                 1020 non-null   str
 9   phone                 1020 non-null   int64
 10  performance_score     1020 non-null   str
 11  remote_work           1020 non-null   bool
 12  department            1020 non-null   object
 13  region                1020 non-null   object
 14  duplicate_email_flag  1020 non-null   bool
dtypes: bool(2), datetime64[us](1), float64(2), int64(2), object(2), str(6)
memory usage: 105.7+ KB

Phone numbers are identifiers, not numeric values.
Casting to decimal and remove minuse only.

In [38]:
employees_df['phone'] = pd.to_numeric(employees_df['phone'].astype(str).str.replace('-',''))
employees_df['phone'].sample(5)

355     8955296385
376     5381649382
121     9639907675
761     7278532425
1011    6511893939
Name: phone, dtype: int64

In [39]:
employees_df['performance_score']=employees_df['performance_score'].str.capitalize()
# in employees_df['performance_score'], every thing is code
# we can standerize the performance_score to 1,2,3,4 value for optimazing the speed of reading

Casting the remore_work column to int for data profermance

In [40]:
employees_df['remote_work']=employees_df['remote_work'].astype(int)
# column already boolean type so we decide to convert it to int for data profermance

In [41]:
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           1020 non-null   str
 1   first_name            1020 non-null   str
 2   last_name             1020 non-null   str
 3   age                   809 non-null    float64
 4   department_region     1020 non-null   str
 5   status                1020 non-null   int64
 6   join_date             1020 non-null   datetime64[us]
 7   salary                996 non-null    float64
 8   email                 1020 non-null   str
 9   phone                 1020 non-null   int64
 10  performance_score     1020 non-null   str
 11  remote_work           1020 non-null   int64
 12  department            1020 non-null   object
 13  region                1020 non-null   object
 14  duplicate_email_flag  1020 non-null   bool
dtypes: bool(1), datetime64[us](1), float64(2), int64(3), object(2), str(6)
memory usage: 112.7+ KB

Handling the missing values in the age and salary columns using the KNN algorithm using the sklearn package
in this algorithm will suppose the neighbor is 5 and weigh is distance to find the nearst k value and fill the
the missing value

In [42]:
from sklearn.impute import KNNImputer
# pip install sklearn

In [43]:
numeric_columns=['age','salary'] # split the numeric columns
categories_columns=['employee_id', 'first_name', 'last_name', 'department_region',
       'status', 'join_date', 'email', 'phone', 'performance_score',
       'remote_work', 'department', 'region', 'duplicate_email_flag'] # split the categories columns

numeric_df=employees_df[numeric_columns]
categories_df=employees_df[categories_columns]

In [44]:
imputer = KNNImputer(n_neighbors=5, weights='distance') # initialize the knnimputer

In [45]:
df_imputed = imputer.fit_transform(numeric_df) # learn the pattern and fill the missing values

In [46]:
df_imputed=pd.DataFrame(df_imputed,columns=numeric_columns) # convert the imputed data to dataframe with the
# numeric columns

In [47]:
employees_df=pd.concat([categories_df,df_imputed], axis=1) 
# combine the new imputed dataframe with the categorical dataframe to get the finall dataframe with filled
# missing values

Reorder the employees_df to the desire order and then remove the unwanted columns

In [48]:
desire_columns_order=['employee_id', 'first_name', 'last_name', 'age', 'region','department',
       'join_date', 'salary', 'email', 'phone','status','performance_score',
       'remote_work', 'duplicate_email_flag']
employees_df = employees_df.reindex(columns=desire_columns_order)

In [49]:
employees_df['age']=employees_df['age'].astype(int)

Re-write the cleaned and transformed data to the csv file and i add another method to re-write the 
data to sql server as another way and show case

In [50]:
employees_df.to_csv(r'.\Dataset\Employees_cleaned_dataset.csv', index=False)